from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
import io
from datetime import datetime


def export_to_pdf(filename: str, domain: str, insights: dict, chat_history: list) -> bytes:
    """
    Generates a professional PDF report with:
    - Document metadata
    - Extracted key insights per domain section
    - Full Q&A conversation history
    Returns PDF as bytes for Streamlit download.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=22,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=6,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#666666"),
        spaceAfter=20,
        alignment=TA_CENTER,
    )
    section_style = ParagraphStyle(
        "SectionHeader",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=16,
        spaceAfter=6,
        borderPad=4,
    )
    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#333333"),
        leading=16,
        spaceAfter=8,
    )
    qa_q_style = ParagraphStyle(
        "QAQuestion",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#1a1a2e"),
        fontName="Helvetica-Bold",
        spaceBefore=10,
        spaceAfter=4,
    )
    qa_a_style = ParagraphStyle(
        "QAAnswer",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#333333"),
        leading=16,
        leftIndent=12,
        spaceAfter=4,
    )

    story = []

    # Header
    story.append(Paragraph("DocuSense Analysis Report", title_style))
    story.append(Paragraph(
        f"Document: {filename} &nbsp;|&nbsp; Domain: {domain} &nbsp;|&nbsp; {datetime.now().strftime('%B %d, %Y')}",
        subtitle_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dddddd")))
    story.append(Spacer(1, 0.4*cm))

    # Key Insights section
    if insights:
        story.append(Paragraph("Key Insights Extracted", section_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#eeeeee")))
        story.append(Spacer(1, 0.2*cm))

        for section_title, content in insights.items():
            story.append(Paragraph(f"• {section_title}", qa_q_style))
            story.append(Paragraph(content, body_style))

    story.append(Spacer(1, 0.4*cm))

    # Q&A History section
    qa_pairs = []
    for i in range(0, len(chat_history) - 1, 2):
        if chat_history[i]["role"] == "user" and chat_history[i+1]["role"] == "assistant":
            qa_pairs.append((chat_history[i]["content"], chat_history[i+1]["content"]))

    if qa_pairs:
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#dddddd")))
        story.append(Paragraph("Question & Answer History", section_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#eeeeee")))
        story.append(Spacer(1, 0.2*cm))

        for i, (q, a) in enumerate(qa_pairs, 1):
            story.append(Paragraph(f"Q{i}: {q}", qa_q_style))
            story.append(Paragraph(a, qa_a_style))

    # Footer note
    story.append(Spacer(1, 0.6*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#dddddd")))
    story.append(Paragraph(
        "Generated by DocuSense — AI-powered document intelligence.",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8,
                       textColor=colors.HexColor("#999999"), alignment=TA_CENTER)
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()